### ISSUE TITLE
Guzzle Namespace issues

### ISSUE THREAD

**Issue by nmkr** [tjphippen/docusign#1]
looks like the namespace change to GuzzleHttp\Client; ? ..

**Comment by nmkr** [comment]
to be clear.. in guzzle 5.3 some variables changed..

namespace to GuzzleHttp\Client

and Client Details changed too..

base_uri -> base_url and headers had do be wrapped in defaults => ['headers' => $this->getHeaders()]

**Comment by tjphippen** [comment]
Thanks for the notice. I had actually made these changes previously on my local install but negated to commit them.
