### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by blakethepatton** [tjphippen/docusign#10]
It'd be great to be able to add our own custom fields for the Guzzle Requests. In my situation, I need to add in a couple curl constants to the requests so that ssl actually works. I'll try and put together a MR for this.

**Comment by tjphippen** [comment]
Thanks for this. I have quite a few upgrades to this I made previously but haven't had time to merge them.

**Comment by tjphippen** [comment]
Merged PR, forgot to close issue :P
