### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by fernac03** [tjphippen/docusign#19]
how to add document do envelope
can some one  post a example ?
thanks

**Comment by tjphippen** [comment]
https://github.com/tjphippen/docusign/blob/master/src/Docusign.php#L148 
FYI not all possible Docusign API methods are implemented in this package.

**Comment by tjphippen** [comment]
See https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/update/ 
`$data = ['accountId' => STRING, 'documentId' => STRING, 'envelopeId' => STRING];
Docusign::updateEnvelopeDocuments($envelopeId, $data)`

When I next update this it'll have 
`$envelope->documents()->update([...])`
