### ISSUE TITLE
how i create a template

### ISSUE THREAD

**Issue by mahendra-redrock** [tjphippen/docusign#4]
Dear TJ Phippen,

I am using "tjphippen/docusign" all function are working properly in web but now i am trying to add new function for Creating template in Docusign.
I am adding New function in "Docusign.php" with same pattern what you are using..

All yours functions are working perfectly like (createEnvelope, getEnvelopeTabs) etc.

My code is mentioned below :-
1)
public function createTemplate($data) {
        $request = $this->client->post('templates/', ['json' => $data]);
        return $temp = $this->rawJson($request);
 }

2)  Creating controller "DocusignController":-

$create_Temp = Docusign::createTemplate(array(
   'emailsubject'   => 'Demo Envelope Subject', // Subject of email sent to all recipients
   'documents'  => array('name'     => 'My name',
   'documentId'    => '123456'),
    'recipients' => array(
    'signers'=> array(
       'tabs'=> array(
          'signHereTabs'=> array(
              'name'=> 'SignatureTab1',
              'pageNumber'=> '1',
              'documentId'=> '123456',
              'yPosition'=> '100',
              'xPosition'=> '100'
            )
        ),
        'routingOrder'=> '1',
        'recipientId'=> '1',
        'clientUserId'=> 'Docusign User Id',
        'name'=> 'my name',
        'email'=> 'Docusign Account Email'

```
)
```

  ),
    'envelopeTemplateDefinition'  => array(
        'templateId'     => '3232329887', 'name'=>'Hellotestdocbycode',
        'description'     => 'asdfa sd asdf as', 'password'=>'123123',
        'pageCount'=>'1', 'folderName' => 'test',
        'folderId' => 'Folder ID', 
        'owner' => array('userName'=>'User Name', 'email'=>'Docusign Account Email', 
        'userId'=>'Docusign User ID', 
        'userType'=>'', 'userStatus'=>'active')
        ),  
    ));

but I am facing Issue  :--

ClientException in laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 111: Client error: `POST https://demo.docusign.net/restapi/v2/accounts/17a20f1a-83cb-40e2-a5e9-07da73190dbf/templates/` resulted in a `400 Bad Request` response:
{
"errorCode": "INVALID_REQUEST_BODY",
"message": "The request body is missing or improperly formatted. Cannot des (truncated...)

Please help me resolve my issue.

Thanks

**Comment by tjphippen** [comment]
Sorry for the late response. While you're including envelopeTemplateDefinition it's probably not in the exact format as stated here: https://docs.docusign.com/esign/restapi/Templates/Templates/create/  I'll be releasing an update in the next week & will try to just include this method for you.
