### ISSUE TITLE
Throwing exception with laravel 5.4 and php 7.1

### ISSUE THREAD

**Issue by uvshimla** [tjphippen/docusign#7]
I am trying to install this package with laravel 5.4 and php 7.1. But it throwing **minimum-stability** exception. I am trying to install by using composer. Kindly guide me what I am doing wrong.
Thanks in advance.

**Comment by tjphippen** [comment]
This is due to your composer.json "minimum-stability": "stable" as this package is "dev". Change your stability from stable to dev & it'll work. Also the next release should be stable anyway.
